version: '3.7'

services:
  db:
    container_name: dbsaiyancel
    image: mariadb:10
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes: 
      - dbstore:/var/lib/mysql

  server:
    container_name: server
    build:
      context: Server/
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    links:
      - db 
    volumes:
      - ./Server:/usr/src/app
      - /usr/src/app/node_modules
      
  client:
    container_name: client
    build: 
      context: Client/
      dockerfile: Dockerfile
    environment:
      API: ${API}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./Client:/usr/src/app
      - /usr/src/app/node_modules

volumes: 
  dbstore: