version: '3.7'

services:
  db:
    container_name: saiyancel_db
    image: mongo
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
    ports: 
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes: 
      - dbstore:/data/db

  server:
    container_name: server
    build:
      context: Server/
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      API_KEY: ${API_KEY}
      AUTH_DOMAIN: ${AUTH_DOMAIN}
      DATA_BASE_URL: ${DATA_BASE_URL}
      PROJECT_ID: ${PROJECT_ID}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      MESSAGIND_SENDER_ID: ${MESSAGIND_SENDER_ID}
      APP_ID: ${APP_ID}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    links:
      - db 
    volumes:
      - ./Server:/usr/src/app
      - /usr/src/app/node_modules
      
  client:
    container_name: client
    build: 
      context: Client/
      dockerfile: Dockerfile
    environment:
      API: ${API}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./Client:/usr/src/app
      - /usr/src/app/node_modules

volumes: 
  dbstore: